# Standalone Docker Compose for Retail Database
# Use this if you want to run just the database without the full dev container

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: retail-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: retail_db
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./01-create-schema.sql:/docker-entrypoint-initdb.d/01-create-schema.sql
      - ./02-populate-data.sql:/docker-entrypoint-initdb.d/02-populate-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense_user -d expense_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

# Usage:
# docker-compose -f docker-compose.standalone.yml up -d
# 
# Connect with:
# docker exec -it expense-tracker-db psql -U expense_user -d expense_tracker
#
# Stop with:
# docker-compose -f docker-compose.standalone.yml down
